server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/future
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver

