server:
  port: 6660

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/future
    username: postgres
    password: Admin123
    driverClassName: org.postgresql.Driver

